name: rhs_player_example
description: "Demonstrates how to use the rhs_player plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  rhs_player:
    path: ../
  rxdart: ^0.28.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - films.json
    - assets/controls/
