name: rhs_player
description: "Native network-only video player with custom Android (ExoPlayer) and iOS (AVPlayer) engines."
version: 0.5.0
homepage: https://github.com/unger1984/rhs_player
repository: https://github.com/unger1984/rhs_player
issue_tracker: https://github.com/unger1984/rhs_player/issues
topics:
  - video
  - player
  - media
  - drm
  - thumbnails

environment:
  sdk: ^3.8.1
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.rhs_player
        pluginClass: RhsPlayerPlugin
      ios:
        pluginClass: RhsPlayerPlugin

  # assets:
  #   - assets/
